name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:

  standard:

    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
        code:
          - sort

    defaults:
      run:
        shell: bash -l {0}

    name: "${{ matrix.code }} • ${{ matrix.runs-on }}"
    runs-on: ${{ matrix.runs-on }}

    steps:

    - name: Basic GitHub action setup
      uses: actions/checkout@v2

    - name: Set conda environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment.yaml
        environment-name: myenv

    - name: Configure
      working-directory: ${{ matrix.code }}
      run: cmake -Bbuild

    - name: Compile
      working-directory: ${{ matrix.code }}/build
      run: cmake --build .

    - name: Example
      working-directory: ${{ matrix.code }}/build
      run: |
        cp ../example.py .
        python example.py
